#| -*-: mode: common-lisp -*-
exec sbcl --script $0 $* # |#
(defun xxnreverse2 (x y z)
  (rplacd y z)
  (if (not x)  y  (xxnreverse2 (cdr x) x y)))
(defun xxnreverse (x)
  (if (not x) nil (xxnreverse2 (cdr x) x nil)))
(defun xnreverse  (x)                 (xnreverse2      x   nil))
(defun  xreverse  (x)                 ( xreverse2      x   nil))
(print (xxnreverse (list)))
(print (xxnreverse (list 1)))
(print (xxnreverse (list 1 2)))
(print (xxnreverse (list 1 2 3)))
(print (xxnreverse (list 1 2 3 4)))
(print (xxnreverse (list 1 2 3 4 5)))
(print (xxnreverse (list 1 2 3 4 5 6)))
